name: Node.js CI
on:
  schedule:
    # Runs every 4 hours
    - cron: '*/30 * * * *'
  workflow_dispatch:  # This enables the manual trigger button
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Start application
      run: npm start &
    - name: Wait to exit
      run: sleep 30m
